### ISSUE TITLE
unary branch

### ISSUE THREAD

**Issue by www516717402** [Howal/DNL-Object-Detection#1]
Thank your for great project. I have not find **unary branch** in your [code](https://github.com/Howal/DNL-Object-Detection/blob/a8fbf7c3c57feb268830435b53a270accd0df3fa/mmdet/models/plugins/non_local.py#L177). This DNL modules non-complete?

**Comment by Howal** [comment]
Hi, thank you for your interest. The core code of dnl block is [here](https://github.com/Howal/DNL-Object-Detection/blob/a8fbf7c3c57feb268830435b53a270accd0df3fa/mmdet/ops/nl_gc_block.py).
Since it is still in progress, some codes are in disorder.
