### ISSUE TITLE
Code Question

### ISSUE THREAD

**Issue by Ahnsun** [Howal/DNL-Object-Detection#12]
https://github.com/Howal/DNL-Object-Detection/blob/6ae88842d6237a465559c420c610444bcb2d9405/mmdet/ops/nl_gc_block.py#L151
Why do the matrix multiplication V×(Q×K) before adding Wm?

**Comment by Howal** [comment]
It follows Eq.12 in our paper.

**Comment by Ahnsun** [comment]
Thanks for your answer,but in the Fig. 2，**Wv** is the last one to be multiplied after adding the **Wm**,and in the code,value(Wv) is multiplied before adding the **Wm**

**Comment by Howal** [comment]
Vx(QxK+Wm) = Vx(QxK) + VxWm
We follow the left term in Fig 2 and the right term in the code.
