### ISSUE TITLE
version question

### ISSUE THREAD

**Issue by tingfengwanxiao** [Howal/DNL-Object-Detection#13]
Hello,I use cuda 10.0 and meet the question
//---------------------------------------------------------------
File "/home/hjl/object-detection/DNL-Object-Detection/mmdet/utils/flops_counter.py", line 35, in <module>
    from mmdet.ops.dcn import DeformConv, ModulatedDeformConv
  File "/home/hjl/object-detection/DNL-Object-Detection/mmdet/ops/__init__.py", line 3, in <module>
    from .dcn import (DeformConv, DeformConvPack, DeformRoIPooling,
  File "/home/hjl/object-detection/DNL-Object-Detection/mmdet/ops/dcn/__init__.py", line 1, in <module>
    from .deform_conv import (DeformConv, DeformConvPack, ModulatedDeformConv,
  File "/home/hjl/object-detection/DNL-Object-Detection/mmdet/ops/dcn/deform_conv.py", line 9, in <module>
    from . import deform_conv_cuda
ImportError: libcudart.so.9.2: cannot open shared object file: No such file or directory
//--------------------------------------------------------------------------------------------------------------

is it means I should back cuda to 9.0 ?while the inplace_abn cuda should >10.0

//---------------------------------------------------------------------------------------
NOTE 1: our code requires PyTorch v1.1 or later

NOTE 2: we are only able to provide support for Linux platforms and CUDA versions >= 10.0

NOTE 3: in general, it is not possible to load weights from a network trained with standard BN into an InPlace-ABN network without severe performance degradation, due to the different handling of BN scaling parameters

To install the package containing the iABN layers:

pip install inplace-abn

**Comment by Howal** [comment]
We use CUDA 9.2 for our code. ABN's previous version [(for example)](https://github.com/mapillary/inplace_abn/tree/v1.0.6) does support CUDA 9.2.
Besides, we used ABN just because at that time pytorch's syncbn has some unknown bugs. You can also use a new version of pytorch and replace abn's syncbn with pytorch's syncbn.

**Comment by tingfengwanxiao** [comment]
ok,thank you,I understand.
