### ISSUE TITLE
Eq(12) in the paper

### ISSUE THREAD

**Issue by houhouhouhou11** [Howal/DNL-Object-Detection#5]
hello,thanks for your fantastic work!
   I have some questions in the Eq(12), the shape of the former is(b,THW,THW),the shape of the latter is (b,1,THW),how about the addation.  sorry， I don't know whether my understanding is correct or not .
   thank you very much!

**Comment by Howal** [comment]
You are right. As you can see in Fig2. (d), the latter term is first expanded then added to the former term.

**Comment by houhouhouhou11** [comment]
> You are right. As you can see in Fig2. (d), the latter term is first expanded then added to the former term.

thanks for your reply. Can you tell me how can i expand from one value to T*H*W values.Because i have not found the DNL block.I just found the nl block.
Thank you very much!

**Comment by Howal** [comment]
It's done by [PyTorch](https://pytorch.org/docs/master/notes/broadcasting.html#broadcasting-semantics) automatically.
