### ISSUE TITLE
Eq.2   the  μ  is acculated on  the channel dimension or the height*width weigth 

### ISSUE THREAD

**Issue by houhouhouhou11** [Howal/DNL-Object-Detection#7]
Hello,thanks for your perfect work.
      I  have some question about Eq.2 ,μq is the mean of all query samples ,but i don't know which dimension it is acculate mean on   ,channel dimension or the height*width weigth ?

thank you very much!

**Comment by Howal** [comment]
We use μ over H*W as default.
